name: build_artifacts

on:
  workflow_dispatch:

run-name: ${{ github.ref_name }} -> build_artifacts ( ${{ github.run_attempt }} )

jobs:
  build_artifacts:
    name: build_artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

    - name: Echo current date and time
      id: datetime
      run: |
        echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Get version
      id: get_version
      run: |
        export version=$(grep "^version = " pyproject.toml | head -1 | sed 's/version = "\([^"]*\)".*/\1/')
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Build package
      run: uv build

    - name: Archive all artifacts in dist/
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: dist-v${{ steps.get_version.outputs.version }}
        path: dist/
